# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.empty((3,3,3))
print(x)

[[[6.23042070e-307 3.56043053e-307 1.60219306e-306]
  [7.56571288e-307 1.89146896e-307 1.37961302e-306]
  [1.05699242e-307 8.01097889e-307 1.78020169e-306]]

 [[7.56601165e-307 1.02359984e-306 1.33510679e-306]
  [2.22522597e-306 1.33511018e-306 6.23057689e-307]
  [1.86921279e-306 8.90098127e-307 1.78020848e-306]]

 [[1.60219035e-306 1.42418172e-306 2.04712906e-306]
  [7.56589622e-307 1.11258277e-307 8.90111708e-307]
  [2.11389826e-307 1.11260619e-306 2.29175545e-312]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [11]:
Z= np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [12]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.39643532 0.77441482 0.7147141  0.08434257 0.66435375]
 [0.85086573 0.74943104 1.         0.67048446 0.64591484]
 [0.56462764 0.41347545 0.88636418 0.71376381 0.        ]
 [0.79598293 0.42791396 0.73462094 0.21513594 0.46141682]
 [0.72991908 0.12313992 0.62382485 0.16640062 0.58785983]]


# 5.  How to find common values between two arrays?

In [13]:
import numpy as np
array1 = np.array([[10,20,30],[40,50,60]])
print("Array1: ",array1)
array2 = np.array([[10, 30, 40],[70,80,60]])
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [[10 20 30]
 [40 50 60]]
Array2:  [[10 30 40]
 [70 80 60]]
Common values between two arrays:
[10 30 40 60]


# 6.How to get the dates of yesterday, today and tomorrow?

In [16]:
import numpy as np
yestrday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yestrday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-29
Today:  2020-07-30
Tomorrow:  2020-07-31


# 7. Consider two random array A and B, check if they are equal

In [20]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 0 0 1 0]
Second array:
[0 0 0 0 0 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [23]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.64747744 0.69441978 0.91684121 0.12424107 0.22655949 0.97896218
 0.12292097 0.83186816 0.13593884 0.3660376 ]
Maximum value replaced by 0:
[0.64747744 0.69441978 0.91684121 0.12424107 0.22655949 0.
 0.12292097 0.83186816 0.13593884 0.3660376 ]


# 9. How to print all the values of an array?

In [26]:
import numpy as np
x = np.zeros((4, 4))
print(x)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [27]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.8901098  0.55951039 0.9641541  0.85771312 0.48669122 0.86632472
  0.25678951 0.41345438 0.45856092 0.74955576]
 [0.09612316 0.28472219 0.60161088 0.58880493 0.75987385 0.20608495
  0.00317453 0.45298494 0.91610059 0.04624488]
 [0.44650273 0.20528261 0.10017329 0.20006504 0.53546175 0.79118882
  0.87770091 0.95508958 0.05362332 0.47661784]
 [0.69229391 0.31195586 0.91640021 0.09136926 0.69374611 0.45230662
  0.40213548 0.10854364 0.32762315 0.06347678]
 [0.26959735 0.60038986 0.83091963 0.83509025 0.5167447  0.89488139
  0.61577984 0.35797014 0.20979678 0.00558763]]

Subtract the mean of each row of the said matrix:

[[ 0.23982341 -0.090776    0.31386771  0.20742672 -0.16359517  0.21603832
  -0.39349688 -0.23683201 -0.19172547  0.09926937]
 [-0.29944933 -0.1108503   0.20603839  0.19323244  0.36430136 -0.18948754
  -0.39239796  0.05741244  0.5205281  -0.34932761]
 [-0.01766786 -0.25888798 -0.3639973  -0.26410555  0.07129116  0.32701823
   0.41353032  0.49091899 -0.4

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [28]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))

print(Z)

[2. 3. 1. 5. 4. 1. 2. 6. 4. 2.]


In [29]:
np.add.at(Z, I, 1)

print(Z)

[ 3.  5.  1.  9.  7.  1.  3. 11.  7.  3.]


# 12.How to get the diagonal of a dot product?

In [30]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([ 3, 30, 24])

# 13.How to find the most frequent value in an array?

In [31]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[6 7 3 0 8 9 7 5 8 9 4 5 7 4 5 0 6 9 2 9 2 5 7 4 5 7 2 8 9 7 5 3 2 0 9 8 6
 5 4 3 5 0 8 4 0 7 5 1 7 0]
rank: 5


# 14.How to get the n largest values of an array

In [32]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9995 9996]


# 15.How to create a record array from a regular array?

In [33]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

In [34]:
print(Z)
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
